version: "3.8"
services:
  nodeserver:
    container_name: docker-web-app
    build:
      context: ./app
    ports:
      - "3000:8080"
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
